In [12]:
import math
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import tree, metrics
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix


In [ ]:
#Реализовать классы нейросетей по аналогии с классом OurNeuralNetwork.
#Данные нейросети:
#− три входа (𝑥1, 𝑥2, 𝑥3
#);
#− три нейрона в скрытых слоях (ℎ1, ℎ2, ℎ3);
#− выход (𝑜1).
#Нейроны имеют идентичные веса и пороги:
# − 𝑤 = [0.5, 0.5, 0.5]
# − 𝑏 = 0
# Данные нейросети:
# − два входа (𝑥1, 𝑥2);
# − два нейрона в скрытых слоях (ℎ1, ℎ2);
# − два выхода (𝑜1, 𝑜2
# ).
# Нейроны имеют идентичные веса и пороги:
# − 𝑤 = [1, 0];
# − 𝑏 = 1.

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
    def feedforward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias
        return sigmoid(total)

class OurNeuralNetwork:
    
    def __init__(self):
        weights = np.array([0.5, 0.5, 0.5])
        bias = 0
        self.h1 = Neuron(weights, bias)
        self.h2 = Neuron(weights, bias)
        self.h3 = Neuron(weights, bias)
        self.o1 = Neuron(weights, bias)
    
    def feedforward(self, x):
        out_h1 = self.h1.feedforward(x)
        out_h2 = self.h2.feedforward(x)
        out_h3 = self.h3.feedforward(x)
        out_o1 = self.o1.feedforward(np.array([out_h1, out_h2, out_h3]))
        return out_o1
    
network = OurNeuralNetwork()
x = np.array([2, 3, 4])
print(network.feedforward(x))

0.8151036049051821


In [6]:
# Реализуйте классы нейронных сетей с использованием других функций
# активации.
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
    def feedforward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias
        return sigmoid(total)

class OurNeuralNetwork:
    
    def __init__(self):
        weights = np.array([0.5, 0.5, 0.5])
        bias = 0
        self.h1 = Neuron(weights, bias)
        self.h2 = Neuron(weights, bias)
        self.h3 = Neuron(weights, bias)
        self.o1 = Neuron(weights, bias)
    
    def feedforward(self, x):
        out_h1 = self.h1.feedforward(x)
        out_h2 = self.h2.feedforward(x)
        out_h3 = self.h3.feedforward(x)
        out_o1 = self.o1.feedforward(np.array([out_h1, out_h2, out_h3]))
        return out_o1
    
network = OurNeuralNetwork()
x = np.array([2, 3, 4])
print(network.feedforward(x))

0.8151036049051821


In [ ]:

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
    def feedforward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias
        return sigmoid(total)

class OurNeuralNetwork:
    
    def __init__(self):
        weights = np.array([0.5, 0.5, 0.5])
        bias = 0
        self.h1 = Neuron(weights, bias)
        self.h2 = Neuron(weights, bias)
        self.h3 = Neuron(weights, bias)
        self.o1 = Neuron(weights, bias)
    
    def feedforward(self, x):
        out_h1 = self.h1.feedforward(x)
        out_h2 = self.h2.feedforward(x)
        out_h3 = self.h3.feedforward(x)
        out_o1 = self.o1.feedforward(np.array([out_h1, out_h2, out_h3]))
        return out_o1
    
network = OurNeuralNetwork()
x = np.array([2, 3, 4])
print(network.feedforward(x))


def tanh(x):
    return np.tanh(x)

class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
    def feedforward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias
        return tanh(total)

class OurNeuralNetwork:
    
    def __init__(self):
        weights = np.array([0.5, 0.5, 0.5])
        bias = 0
        self.h1 = Neuron(weights, bias)
        self.h2 = Neuron(weights, bias)
        self.h3 = Neuron(weights, bias)
        self.o1 = Neuron(weights, bias)
    
    def feedforward(self, x):
        out_h1 = self.h1.feedforward(x)
        out_h2 = self.h2.feedforward(x)
        out_h3 = self.h3.feedforward(x)
        out_o1 = self.o1.feedforward(np.array([out_h1, out_h2, out_h3]))
        return out_o1
    
network = OurNeuralNetwork()
x = np.array([2, 3, 4])
print(network.feedforward(x))


def ReLU(x):
    return max(0.0, x)

class Neuron:
    def __init__(self, weights, bias):
        self.weights = weights
        self.bias = bias
    def feedforward(self, inputs):
        total = np.dot(self.weights, inputs) + self.bias
        return ReLU(total)

class OurNeuralNetwork:
    
    def __init__(self):
        weights = np.array([0.5, 0.5, 0.5])
        bias = 0
        self.h1 = Neuron(weights, bias)
        self.h2 = Neuron(weights, bias)
        self.h3 = Neuron(weights, bias)
        self.o1 = Neuron(weights, bias)
    
    def feedforward(self, x):
        out_h1 = self.h1.feedforward(x)
        out_h2 = self.h2.feedforward(x)
        out_h3 = self.h3.feedforward(x)
        out_o1 = self.o1.feedforward(np.array([out_h1, out_h2, out_h3]))
        return out_o1
    
network = OurNeuralNetwork()
x = np.array([2, 3, 4])
print(network.feedforward(x))

0.8151036049051821
0.9050813365686774
6.75


In [14]:
# Используйте классы MLPClassified и MLPRegressor для классификации и
# регрессии произвольных данных из интернета. Проведите анализ
# атрибуты, полученных моделей.
# Для классификации можете взять набор данных Ирисов:
# https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f
# 7d537619d0e07d5ae3/iris.csv
# а для регрессии датасет зависимости заработной платы от опыта работы:
# https://raw.githubusercontent.com/AnnaShestova/salary-years-simple-linearregression/master/Salary_Data.csv

url = r'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
dataset = pd.read_csv(url)

X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size = 0.80, test_size = 0.20, stratify = Y, random_state = 123)

mlp_classifier = MLPClassifier(max_iter = 1000).fit(X_train, Y_train)
Y_pred = mlp_classifier.predict(X_test)

df = pd.DataFrame({'Actual': Y_test, 'Predicted': Y_pred})
print(df)

print("\nTest Accuracy: %.3f"%mlp_classifier.score(X_test, Y_test))
print('Training Accuracy: %.3f'%mlp_classifier.score(X_train, Y_train))
print(f"\nMatrix of Confusion:\n {confusion_matrix(Y_test, Y_pred)}")
print(f"\nLoss : ", mlp_classifier.loss_)
print(f'Number of Coefs : ', len(mlp_classifier.coefs_))
print(f'Number of Intercepts : ', len(mlp_classifier.intercepts_))
print(f'Number of Iterations for Which Estimator Run : ', mlp_classifier.n_iter_)
print(f'Name of Output Layer Activation Function : ', mlp_classifier.out_activation_)

url = r'https://raw.githubusercontent.com/AnnaShestova/salary-years-simple-linear-regression/master/Salary_Data.csv'
data = pd.read_csv(url)
#print(dataset.head())

X = data.iloc[:, :-1].values
y = data.iloc[:, 1].values


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
mlp = MLPRegressor(hidden_layer_sizes=(100, 50), max_iter=1000)
mlp.fit(X_train, y_train)
y_pred = mlp.predict(X_test)

#Оценка качества модели:
from sklearn.metrics import mean_squared_error, r2_score

print("Mean squared error: %.2f" % mean_squared_error(y_test, y_pred))
print("R2 score: %.2f" % r2_score(y_test, y_pred))

print(mlp.n_layers_) 
print(mlp.hidden_layer_sizes) 
print(mlp.coefs_)

        Actual   Predicted
0   Versicolor  Versicolor
1       Setosa      Setosa
2    Virginica   Virginica
3    Virginica   Virginica
4       Setosa      Setosa
5       Setosa      Setosa
6    Virginica   Virginica
7   Versicolor   Virginica
8    Virginica   Virginica
9       Setosa      Setosa
10      Setosa      Setosa
11  Versicolor  Versicolor
12   Virginica   Virginica
13  Versicolor  Versicolor
14   Virginica   Virginica
15  Versicolor  Versicolor
16      Setosa      Setosa
17      Setosa      Setosa
18      Setosa      Setosa
19      Setosa      Setosa
20      Setosa      Setosa
21   Virginica   Virginica
22   Virginica   Virginica
23  Versicolor  Versicolor
24   Virginica   Virginica
25   Virginica   Virginica
26  Versicolor  Versicolor
27  Versicolor  Versicolor
28  Versicolor   Virginica
29  Versicolor  Versicolor

Test Accuracy: 0.933
Training Accuracy: 0.992

Matrix of Confusion:
 [[10  0  0]
 [ 0  8  2]
 [ 0  0 10]]

Loss :  0.04949916411590018
Number of Coefs :  2
Number

c:\Users\Kirill\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
