In [1]:
import numpy as np
import pandas as pd


In [38]:
# 1.3.1 Задание Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.


Z = np.ones((8,8), dtype = int)
Z[1::2, ::2] = 0
Z[::2, 1::2] = 0
print(Z)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [39]:
#1.3.2 Задание Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания необходимо использовать функцию arrange.

Z = np.zeros((5,5), dtype = int);Z += np.arange(5)
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [28]:
#1.3.3 Задание Задача: Создать массив 3x3x3 со случайными значениями.

print(np.random.random((3, 3, 3)))


[[[0.73931571 0.91402473 0.09553094]
  [0.84129366 0.99336878 0.02402732]
  [0.14811384 0.99428372 0.9804972 ]]

 [[0.74032024 0.54749902 0.90136457]
  [0.04110523 0.01086101 0.16257117]
  [0.59133657 0.75350952 0.49008848]]

 [[0.70184515 0.75975622 0.1317418 ]
  [0.66590381 0.6967674  0.61681251]
  [0.39995934 0.8859282  0.05907753]]]


In [40]:
#1.3.4 Задание Задача: Создать матрицу с 0 внутри, и 1 на границах.

Z = np.ones((5,5), dtype=int); Z[1:-1:,1:-1:] = 0
print(Z)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [27]:
#1.3.5 Задание Задача: Создайте массив и отсортируйте его по убыванию.


Z = np.array(range(14))
Z = Z[::-1]
Z.sort # не нужно
print(Z)

[13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [33]:
#1.3.6 Задание Задача: Создайте матрицу, выведите ее форму, размер и размерность.
Z = np.random.random((5,5))
print("Форма матрицы:",'\n',Z.shape,'\n',"Размер матрицы:",'\n',Z.size,'\n',"Размерность матрицы:",'\n',Z.ndim)




Форма матрицы: 
 (5, 5) 
 Размер матрицы: 
 25 
 Размерность матрицы: 
 2


In [54]:
#2.3.1 Задание Задача: Найдитн евклидово расстояние между двумя Series (точками) a и b, неиспользуя встроенную формулу.
print(pd.Series([1,2,3,4,5]),'\n',
      pd.Series({'a':1, 'b':2, 'c':3}),'\n',
      pd.Series(np.array([1,2,3,4,5]), ['a', 'b', 'c', 'd', 'e']),)


0    1
1    2
2    3
3    4
4    5
dtype: int64 
 a    1
b    2
c    3
dtype: int64 
 a    1
b    2
c    3
d    4
e    5
dtype: int64


In [57]:
#2.3.2 Задание Задача: Найдите в Интернете ссылку на любой csv файл и сформируйте из него фрейм данных (например, коллекцию фреймов данных можно найти здесь: https://github.com/akmand/datasets).

url = "https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv"
df = pd.read_csv(url)

print(df.head())


      crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2  


In [59]:
#2.3.3 Задание Задача: Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7.
dataFrame = pd.DataFrame()
dataFrame['Имя'] = ['Кирилл Татарстан', 'Юра Авган']
dataFrame['Возраст'] = [12,35]
dataFrame['Скакуны'] = [True, False]
dataFrame

Имя  Возраст  Скакуны
0  Кирилл Татарстан       12     True
1         Юра Авган       35    False

In [24]:
#Загрузить фрейм данных по ссылке: https://raw.githubusercontent.com/akmand/datasets/master/iris.csv. Необходимо выполнить нормализацию первого числового признака
#(sepal_length_cm) с использованием минимаксного преобразования, а
#второго (sepal_width_cm) с задействованием z-масштабирования
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
data = pd.read_csv(url)

scaler_minmax = MinMaxScaler()
scaler_z = StandardScaler()

data['sepal_length_cm_normalized'] = scaler_minmax.fit_transform(data[['sepal_length_cm']])
data['sepal_width_cm_normalized'] = scaler_z.fit_transform(data[['sepal_width_cm']])

print(data.head())


   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species  \
0              5.1             3.5              1.4             0.2  setosa   
1              4.9             3.0              1.4             0.2  setosa   
2              4.7             3.2              1.3             0.2  setosa   
3              4.6             3.1              1.5             0.2  setosa   
4              5.0             3.6              1.4             0.2  setosa   

   sepal_length_cm_normalized  sepal_width_cm_normalized  
0                    0.222222                   1.032057  
1                    0.166667                  -0.124958  
2                    0.111111                   0.337848  
3                    0.083333                   0.106445  
4                    0.194444                   1.263460  
